[package]
name = "generate-schema"
version = "0.1.0"
edition = "2024"

[dependencies]
flow-server = { version = "0.0.0", path = "../flow-server", default-features = false }
schemars = "1.2.0"
serde_json = { version = "1.0.149", features = ["preserve_order"] }
