[package]
name = "mpl-core-candy-machine-core"
version = "0.0.0"
edition = "2024"

[dependencies]
# branch: merged
anchor-lang = { git = "https://github.com/space-operator/anchor", rev = "6469201c5399f95f9414839282ea91471bd20260" }