name: Rust

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'no-test') }}
    name: Unit test
    runs-on: self-hosted
    permissions:
      checks: write
      contents: read
    env:
      SOLANA_DEVNET_URL: ${{ secrets.SOLANA_DEVNET_URL }}
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
          override: true
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --quiet --tests --
            -D clippy::dbg_macro
            -D clippy::print_stdout
            -D clippy::print_stderr
            -A clippy::too_many_arguments
      - name: Assert Cargo.lock unchanged
        run: .github/assert_cargo_lock_unchanged.bash
      - name: Build tests
        run: cargo test --quiet --no-run
      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3
      - name: Run tests
        run: cargo test -- --skip need_key_
